### ISSUE TITLE
Private contributions & Output on main branch

### ISSUE THREAD

**Issue by mohammedawaiskhan** [Platane/Platane#11]
- Is there a way to include private contributions? 
- When I changed the result branch from output to main, the workflow deleted everything else and only the two output files were left. is there a way to add these output files without deleting everything else? 

I'm a novice developer so I don't know much about Github actions. Could you help me resolve the above issues?

**Comment by Platane** [comment]
hello, there is a discussion about private contributions here : https://github.com/Platane/snk/issues/105

there is probably ways to push the files into the main branch. you can try to run basic git command, or use an action that does that

**Comment by mohammedawaiskhan** [comment]
Private contributions issue is resolved. As for output on main branch, I'll eventually learn GitHub actions... Thanks for the help.
