### ISSUE TITLE
Error while running workflow

### ISSUE THREAD

**Issue by if1eight0sty** [Platane/Platane#9]
## The process '/usr/bin/git' failed with exit code 128
I am getting this message while running the workflow.

**Comment by Platane** [comment]
It seems like an issue with the github_token, could you provide your workflow file ?

**Comment by Platane** [comment]
it seems like I had one related issue on mine https://github.com/Platane/Platane/actions/runs/5779645880

It might have been due to an temporary outage of github api. It seems back to normal

**Comment by if1eight0sty** [comment]
https://github.com/if1eight0sty/if1eight0sty/blob/main/.github/workflows/main.yml
here is my file. Also, fyi, i haven't created any github_token. Can this possibly be the cause of this error?

**Comment by if1eight0sty** [comment]
its working fine with my friend's account though

**Comment by Platane** [comment]
you should not have to create a token

it seems like your workflow has not run yet https://github.com/if1eight0sty/if1eight0sty/actions/workflows/main.yml

**Comment by if1eight0sty** [comment]
Actually, i have deleted the workflow, it had error so
here is the run wokflow with the error: https://github.com/if1eight0sty/if1eight0sty/actions/runs/5795930174

**Comment by Platane** [comment]
that's seems to be an issue with the ghaction-github-pages action

Take a look at https://github.com/crazy-max/ghaction-github-pages/issues/183

**Comment by if1eight0sty** [comment]
Thank you it helped❤️❤️

```
permissions: 
  contents: write
```
  
adding this worked. Here https://github.com/crazy-max/ghaction-github-pages/issues/183
